### ISSUE TITLE
Rename embree-rs in Crates.io?

### ISSUE THREAD

**Issue by RussellHaley** [Twinklebear/embree-rs#11]
Hi, 

I am a down stream user to a Lua C++ bindings project called Sol2. The project is well established and is now set to move on to version 4, rendering the name problematic. We are having a discussion about renaming the project here: https://github.com/ThePhD/sol2/issues/1186

Creates.io is the outstanding resource that keeps the project from adopting the original name of Sol. It was noted that you own a crate.io package called sol but have since renamed your project to embree-rs. I/we were wondering if you are looking to also rename your crate.io package to embree-rs? If you did free the name,  ThePhantomDerpstorm could simplify the naming of his project. Lua means moon in Portuguese and provides C bindings, it is very fitting that the C++ bindings are called Sol or Sun. :-)

Thanks for taking the request under consideration. Have a great day!

**Comment by Twinklebear** [comment]
Hi, yes this crate has moved to the https://crates.io/crates/embree name on crates, so I don't need the sol crate name. I'd be happy to pass it on to the Lua bindings, and agree Sol is a great name for that project :D . I'll check in on the issue on the sol2 repo about who to hand the ownership to
