### ISSUE TITLE
How to custom intersection filter?

### ISSUE THREAD

**Issue by matthiascy** [Twinklebear/embree-rs#12]
Hi, I want to know if it's possible to use filter functions from rust side? Or should I define the function following the C convention as declared in sys module? Thanks!

**Comment by Twinklebear** [comment]
Hi @matthiascy , right now this isn't possible through the Rust API as I haven't set up any support for filter functions/other callbacks Embree can use. So at the moment you'd need to do this through the sys crate API and define a C-callable Rust function that Embree can call.

**Comment by matthiascy** [comment]
Thank you for the response!
